DROP TABLE V2_CONTACT;
DROP TABLE V2_CONTACT_GROUP;




CREATE TABLE V2_CONTACT_GROUP
(
	GROUP_ID             NUMBER NOT NULL ,
	PARENT_GROUP_ID      NUMBER NULL ,
	GROUP_NAME           VARCHAR2(500) NOT NULL ,
	COMPANY_ID           NUMBER NOT NULL ,
	TYPE_CODE            CHAR(1) NULL ,
	CREATION_DATE        DATE NOT NULL ,
	CREATE_ID            NUMBER NOT NULL ,
	MODIFIED_DATE        DATE NULL ,
	MODIFY_ID            NUMBER NULL ,
	DEL_YN               NUMBER(1) NOT NULL 
);


ALTER TABLE V2_CONTACT_GROUP 
    ADD CONSTRAINT V2_CONTACT_GROUP_FK FOREIGN KEY (COMPANY_ID) REFERENCES V2_COMPANY (COMPANY_ID)
;



CREATE UNIQUE INDEX V2_CONTACT_GROUP_PK ON V2_CONTACT_GROUP
(GROUP_ID   ASC);



ALTER TABLE V2_CONTACT_GROUP
	ADD CONSTRAINT  V2_CONTACT_GROUP_PK PRIMARY KEY (GROUP_ID);


ALTER TABLE V2_CONTACT_GROUP
	ADD (CONSTRAINT V2_CONTACT_GROUP_FK2 FOREIGN KEY (PARENT_GROUP_ID) REFERENCES V2_CONTACT_GROUP (GROUP_ID) ON DELETE SET NULL);



CREATE TABLE V2_CONTACT
(
	CONTACT_ID           NUMBER NOT NULL ,
	NAME                 VARCHAR2(100) NOT NULL ,
	EMAIL                VARCHAR2(100) NULL ,
	PHONE                VARCHAR2(15) NULL ,
	CELL_PHONE           VARCHAR2(15) NULL ,
	TAG                  VARCHAR2(500) NULL ,
	CONTACT_DESC         VARCHAR2(500) NULL ,
	GROUP_ID             NUMBER NOT NULL ,
	CREATION_DATE        DATE NOT NULL ,
	CREATE_ID            NUMBER NOT NULL ,
	MODIFIED_DATE        DATE NULL ,
	MODIFY_ID            NUMBER NULL ,
	DEL_YN               NUMBER(1) NOT NULL 
);



CREATE UNIQUE INDEX V2_CONTACT_PK ON V2_CONTACT
(CONTACT_ID   ASC);



ALTER TABLE V2_CONTACT
	ADD CONSTRAINT  V2_CONTACT_PK PRIMARY KEY (CONTACT_ID);


ALTER TABLE V2_CONTACT 
    ADD CONSTRAINT V2_CONTACT_FK FOREIGN KEY (GROUP_ID) REFERENCES V2_CONTACT_GROUP (GROUP_ID)
;




CREATE TABLE V2_CONTACT_TAG
(
	CONTACT_ID           NUMBER NOT NULL ,
	TAG_ID               NUMBER NOT NULL ,
	CREATION_DATE        DATE NOT NULL ,
	CREATE_ID            NUMBER NOT NULL ,
	MODIFIED_DATE        DATE NULL ,
	MODIFY_ID            NUMBER NULL 
);



CREATE UNIQUE INDEX V2_CONTACT_TAG_PK ON V2_CONTACT_TAG
(CONTACT_ID   ASC,TAG_ID   ASC);



ALTER TABLE V2_CONTACT_TAG
	ADD CONSTRAINT  V2_CONTACT_TAG_PK PRIMARY KEY (CONTACT_ID,TAG_ID);



CREATE TABLE V2_TAG
(
	TAG_ID               NUMBER NOT NULL ,
	TAG_NAME             VARCHAR2(500) NOT NULL ,
	CREATION_DATE        DATE NOT NULL ,
	CREATE_ID            NUMBER NOT NULL ,
	MODIFIED_DATE        DATE NULL ,
	MODIFY_ID            NUMBER NULL ,
	COMPANY_ID           NUMBER NOT NULL 
);



CREATE UNIQUE INDEX V2_TAG_PK ON V2_TAG
(TAG_ID   ASC);



ALTER TABLE V2_TAG
	ADD CONSTRAINT  V2_TAG_PK PRIMARY KEY (TAG_ID);
    
    ALTER TABLE V2_TAG
	ADD CONSTRAINT  V2_TAG_FK FOREIGN KEY (COMPANY_ID) REFERENCES V2_COMPANY (COMPANY_ID);


ALTER TABLE V2_CONTACT_TAG
	ADD (CONSTRAINT V2_CONTACT_TAG_FK FOREIGN KEY (CONTACT_ID) REFERENCES V2_CONTACT (CONTACT_ID));



ALTER TABLE V2_CONTACT_TAG
	ADD (CONSTRAINT V2_CONTACT_TAG_FK2 FOREIGN KEY (TAG_ID) REFERENCES V2_TAG (TAG_ID));
    


