--------------------------------------------------------
--  DDL for Table V2_SOCIAL_ACCOUNT
--------------------------------------------------------

	CREATE TABLE V2_SOCIAL_CONNECT(	
		SOCIAL_CONNECT_ID					INTEGER NOT NULL,	
		OBJECT_TYPE					INTEGER NOT NULL,
		OBJECT_ID						INTEGER NOT NULL,
		PROVIDER_ID					VARCHAR2(255)	NOT NULL,
		PROVIDER_USER_ID 			VARCHAR2(255),
		DISPLAY_NAME				VARCHAR2(255),
		PROFILE_URL					VARCHAR2(255),
		IMAGE_URL						VARCHAR2(255),
		ACCESS_TOKEN				VARCHAR2(255),
		SECRET							VARCHAR2(255),
		REFRESH_TOKEN				VARCHAR2(255),
		EXPIRE_TIME					INTEGER,
		CREATION_DATE				DATE DEFAULT  SYSDATE NOT NULL,
		MODIFIED_DATE				DATE DEFAULT  SYSDATE NOT NULL,
		CONSTRAINT V2_SOCIAL_CONNECT_PK PRIMARY KEY (SOCIAL_CONNECT_ID)
	) ;

	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."SOCIAL_CONNECT_ID" IS 'ID';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."OBJECT_TYPE" IS '데이터 유형';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."OBJECT_ID" IS '데이터 ID';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."PROVIDER_ID" IS '미디어 ID';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."PROVIDER_USER_ID" IS '미디어 계정 ID';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."DISPLAY_NAME" IS '미디어 계정 이름';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."IMAGE_URL" IS '프로파일 URL';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."IMAGE_URL" IS '이미지 URL';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."ACCESS_TOKEN" IS '접근 토큰 값';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."SECRET" IS 'SECRET 값';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."REFRESH_TOKEN" IS '갱신 토큰 값';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."CREATION_DATE" IS '생성일';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT"."MODIFIED_DATE" IS '수정일';
	COMMENT ON TABLE "V2_SOCIAL_CONNECT"  IS '쇼셜 연결 정보 테이블';
		
	 CREATE INDEX "V2_SOCIAL_CONNECT_IDX1" ON "V2_SOCIAL_CONNECT" ("OBJECT_TYPE", "OBJECT_ID"); 
	 CREATE INDEX "V2_SOCIAL_CONNECT_IDX2" ON "V2_SOCIAL_CONNECT" ("PROVIDER_ID"); 
	 CREATE INDEX "V2_SOCIAL_CONNECT_IDX3" ON "V2_SOCIAL_CONNECT" ("PROVIDER_ID", "PROVIDER_USER_ID" ); 
	 
    CREATE TABLE V2_SOCIAL_CONNECT_PROPERTY (
	  SOCIAL_CONNECT_ID    INTEGER NOT NULL,
	  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
	  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
	  CONSTRAINT V2_SOCIAL_CONNECT_PROPERTY_PK PRIMARY KEY (SOCIAL_CONNECT_ID, PROPERTY_NAME)
	);	
	COMMENT ON TABLE      "V2_SOCIAL_CONNECT_PROPERTY"  IS 'WEBSITE 프로퍼티 테이블';
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT_PROPERTY"."SOCIAL_CONNECT_ID" IS 'ID'; 
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
	COMMENT ON COLUMN "V2_SOCIAL_CONNECT_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 	 
	
/
