	    -- =================================================  
		--  MENU	
		-- =================================================		
		CREATE TABLE V2_MENU (
	    	MENU_ID			          INTEGER NOT NULL,
	   		--COMPANY_ID               INTEGER NOT NULL,
		   	NAME                         VARCHAR2(255) NOT NULL,
		   	TITLE                           VARCHAR2(255) NOT NULL,
		   	LOCATION                   VARCHAR2(255),
		    MENU_ENABLED           NUMBER(1, 0)  DEFAULT 1,
			CREATION_DATE            DATE DEFAULT  SYSDATE NOT NULL,
			MODIFIED_DATE            DATE DEFAULT  SYSDATE NOT NULL,	
	    	CONSTRAINT V2_MENU_PK PRIMARY KEY (MENU_ID)	    
	    );		
		COMMENT ON TABLE      "V2_MENU"  IS '메뉴 테이블';
		COMMENT ON COLUMN "V2_MENU"."MENU_ID" IS '메뉴 ID'; 
		--COMMENT ON COLUMN "V2_MENU"."COMPANY_ID" IS '회사 아이디'; 
		COMMENT ON COLUMN "V2_MENU"."NAME" IS '이름'; 		
		COMMENT ON COLUMN "V2_MENU"."TITLE" IS '타이틀 명'; 
		COMMENT ON COLUMN "V2_MENU"."LOCATION" IS 'LOCATION 값'; 				
		COMMENT ON COLUMN "V2_MENU"."MENU_ENABLED" IS '사용여부'; 
		COMMENT ON COLUMN "V2_MENU"."CREATION_DATE" IS '생성을'; 		
		COMMENT ON COLUMN "V2_MENU"."MODIFIED_DATE" IS '수정일'; 
		
		CREATE TABLE V2_MENU_PROPERTY (
		  MENU_ID                     INTEGER NOT NULL,
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT V2_MENU_PROPERTY_PK PRIMARY KEY (MENU_ID, PROPERTY_NAME)
		);	
		COMMENT ON TABLE      "V2_MENU_PROPERTY"  IS '메뉴 프로퍼티 테이블';
		COMMENT ON COLUMN "V2_MENU_PROPERTY"."MENU_ID" IS '메뉴 ID'; 
		COMMENT ON COLUMN "V2_MENU_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
		COMMENT ON COLUMN "V2_MENU_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 		

		CREATE TABLE V2_MENU_XML (
			  MENU_ID                    INTEGER NOT NULL,
			  MENU_DATA               CLOB,
			  CONSTRAINT V2_MENU_XML_PK PRIMARY KEY (MENU_ID)
		);
		
		CREATE TABLE V2_MENU_DATA (
			  MENU_ID                    INTEGER NOT NULL,
			  MENU_DATA               BLOB,
			  CONSTRAINT V2_MENU_DATA_PK PRIMARY KEY (MENU_ID)
		);
		
		-- =================================================  
		--  ATTACHEMENT 	
		-- =================================================		
		CREATE TABLE V2_ATTACHMENT (
	    		ATTACHMENT_ID			  INTEGER NOT NULL,
			  	OBJECT_TYPE                INTEGER NOT NULL,
			  	OBJECT_ID                   INTEGER NOT NULL,	    		
			   	CONTENT_TYPE             VARCHAR2(50)  NOT NULL,			  
			   	FILE_NAME                   VARCHAR2(255)   NOT NULL,
			   	FILE_SIZE                      INTEGER   NOT NULL,
			   	CREATION_DATE            DATE DEFAULT  SYSDATE NOT NULL,
			   	MODIFIED_DATE            DATE DEFAULT  SYSDATE NOT NULL,	
	    	   CONSTRAINT V2_ATTACHMENT_PK PRIMARY KEY (ATTACHMENT_ID)	    
	    );
	    
	    CREATE INDEX V2_ATTACHMENT_OBJ_IDX ON V2_ATTACHMENT( OBJECT_TYPE, OBJECT_ID ) ;	
		COMMENT ON TABLE "V2_ATTACHMENT"  IS '첨부파일 테이블';
		COMMENT ON COLUMN "V2_ATTACHMENT"."ATTACHMENT_ID" IS 'ID'; 
		COMMENT ON COLUMN "V2_ATTACHMENT"."OBJECT_TYPE" IS '첨부파일과 연관된 모델 유형'; 
        COMMENT ON COLUMN "V2_ATTACHMENT"."OBJECT_ID" IS '첨부파일과 연관된 모델 ID';
		COMMENT ON COLUMN "V2_ATTACHMENT"."FILE_NAME" IS '첨부파일 이름'; 
        COMMENT ON COLUMN "V2_ATTACHMENT"."FILE_SIZE" IS '첨부파일 크기';        
		COMMENT ON COLUMN "V2_ATTACHMENT"."CONTENT_TYPE" IS 'CONTENT TYPE 값'; 
		COMMENT ON COLUMN "V2_ATTACHMENT"."CREATION_DATE" IS '생성일'; 
        COMMENT ON COLUMN "V2_ATTACHMENT"."MODIFIED_DATE" IS '수정일';

        CREATE TABLE V2_ATTACHMENT_PROPERTY (
		  ATTACHMENT_ID               INTEGER NOT NULL,
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT V2_ATTACHMENT_PROPERTY_PK PRIMARY KEY (ATTACHMENT_ID, PROPERTY_NAME)
		);	
		COMMENT ON TABLE      "V2_ATTACHMENT_PROPERTY"  IS '첨부파일 프로퍼티 테이블';
		COMMENT ON COLUMN "V2_ATTACHMENT_PROPERTY"."ATTACHMENT_ID" IS '첨부파일 ID'; 
		COMMENT ON COLUMN "V2_ATTACHMENT_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
		COMMENT ON COLUMN "V2_ATTACHMENT_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 		

		CREATE TABLE V2_ATTACHMENT_DATA (
			  ATTACHMENT_ID                    INTEGER NOT NULL,
			  ATTACHMENT_DATA               BLOB,
			  CONSTRAINT V2_ATTACHMENT_DATA_PK PRIMARY KEY (ATTACHMENT_ID)
		);		        
		
		COMMENT ON TABLE "V2_ATTACHMENT_DATA"  IS '첨부파일 데이터 테이블';
		COMMENT ON COLUMN "V2_ATTACHMENT_DATA"."ATTACHMENT_ID" IS 'ID'; 
		COMMENT ON COLUMN "V2_ATTACHMENT_DATA"."ATTACHMENT_DATA" IS '첨부파일 데이터'; 		
		
	    -- =================================================  
		--  IMAGE	
		-- =================================================		
		CREATE TABLE V2_IMAGE (
			  IMAGE_ID                    INTEGER NOT NULL,
			  OBJECT_TYPE                INTEGER NOT NULL,
			  OBJECT_ID                   INTEGER NOT NULL,
			  FILE_NAME                   VARCHAR2(255)   NOT NULL,
			  FILE_SIZE                      INTEGER   NOT NULL,
			  CONTENT_TYPE             VARCHAR2(50)  NOT NULL,			  
			  CREATION_DATE            DATE DEFAULT  SYSDATE NOT NULL,
			  MODIFIED_DATE            DATE DEFAULT  SYSDATE NOT NULL,	
			  CONSTRAINT V2_IMAGE_PK PRIMARY KEY (IMAGE_ID)
		);		        
		
		
		CREATE INDEX V2_IMAGE_OBJ_IDX ON V2_IMAGE( OBJECT_TYPE, OBJECT_ID ) ;	
		COMMENT ON TABLE "V2_IMAGE"  IS '이미지 테이블';
		COMMENT ON COLUMN "V2_IMAGE"."IMAGE_ID" IS 'ID'; 
		COMMENT ON COLUMN "V2_IMAGE"."OBJECT_TYPE" IS '이미지와 연관된 모델 유형'; 
        COMMENT ON COLUMN "V2_IMAGE"."OBJECT_ID" IS '이미지와 연관된 모델 ID';
		COMMENT ON COLUMN "V2_IMAGE"."FILE_NAME" IS '이미지 파일 이름'; 
        COMMENT ON COLUMN "V2_IMAGE"."FILE_SIZE" IS '이미지 파일 크기';        
		COMMENT ON COLUMN "V2_IMAGE"."CONTENT_TYPE" IS 'CONTENT TYPE 값'; 
		COMMENT ON COLUMN "V2_IMAGE"."CREATION_DATE" IS '생성일'; 
        COMMENT ON COLUMN "V2_IMAGE"."MODIFIED_DATE" IS '수정일';
        
        CREATE TABLE V2_IMAGE_DATA (
			  IMAGE_ID                    INTEGER NOT NULL,
			  IMAGE_DATA               BLOB,
			  CONSTRAINT V2_IMAGE_DATA_PK PRIMARY KEY (IMAGE_ID)
		);		        
		
		COMMENT ON TABLE "V2_IMAGE_DATA"  IS '이미지 데이터 테이블';
		COMMENT ON COLUMN "V2_IMAGE_DATA"."IMAGE_ID" IS 'ID'; 
		COMMENT ON COLUMN "V2_IMAGE_DATA"."IMAGE_DATA" IS '이미지 데이터'; 		
		