Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (1,'COMPANY', 11);
Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (2,'USER',11);
Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (3,'GROUP', 11);
Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (4,'ROLE', 11);


Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (16,'IMAGE', 11);
Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (17,'ATTACHMENT',51);
Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (18,'MENU',11);


insert into V2_COMPANY (COMPANY_ID,DISPLAY_NAME,NAME,DESCRIPTION) 
	values (1,'소속없음','PUBLIC','소속없음');
		
		
Insert into V2_GROUP (GROUP_ID,COMPANY_ID,NAME,DESCRIPTION,CREATION_DATE,MODIFIED_DATE,DISPLAY_NAME) 
values (1,1,'PUBLIC_USERS','일반 사용자 그룹', sysdate, sysdate ,'사용자 그룹');


Insert into V2_ROLE (ROLE_ID,NAME,DESCRIPTION,MASK,CREATION_DATE,MODIFIED_DATE) values (4,'ROLE_INSTRUCTOR','강사 롤',0, sysdate, sysdate);
Insert into V2_ROLE (ROLE_ID,NAME,DESCRIPTION,MASK,CREATION_DATE,MODIFIED_DATE) values (1,'ROLE_USER','사용자 롤',0,sysdate,sysdate);
Insert into V2_ROLE (ROLE_ID,NAME,DESCRIPTION,MASK,CREATION_DATE,MODIFIED_DATE) values (2,'ROLE_ADMIN','관리자 롤',0,sysdate,sysdate);
Insert into V2_ROLE (ROLE_ID,NAME,DESCRIPTION,MASK,CREATION_DATE,MODIFIED_DATE) values (3,'ROLE_SYSTEM','시스템 관리자 롤',0,sysdate,sysdate);
Insert into V2_ROLE (ROLE_ID,NAME,DESCRIPTION,MASK,CREATION_DATE,MODIFIED_DATE) values (5,'ROLE_EDU_MNG','교육담당자 롤',0,sysdate,sysdate);
