

		CREATE TABLE V2_PROPERTY (
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT V2_PROPERTY_PK PRIMARY KEY (PROPERTY_NAME)
		); 		
		
    COMMENT ON TABLE "V2_PROPERTY"  IS '응용프로그램 프로퍼티 지원을 위한 테이블';	
		COMMENT ON COLUMN V2_PROPERTY.PROPERTY_NAME    IS '프로퍼티 이름';                      
		COMMENT ON COLUMN V2_PROPERTY.PROPERTY_VALUE   IS '프로퍼티 값';  
		

		CREATE TABLE V2_LOCALIZED_PROPERTY (
		  LOCALE_CODE            VARCHAR2(100)   NOT NULL,
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT V2_LOCALIZED_PROPERTY_PK PRIMARY KEY (LOCALE_CODE, PROPERTY_NAME)
		);
		
    COMMENT ON TABLE "V2_LOCALIZED_PROPERTY"  IS '로케일에 따른 응용프로그램 프로퍼티 지원을 위한 테이블';
		COMMENT ON COLUMN V2_LOCALIZED_PROPERTY.LOCALE_CODE      IS '로케일 코드';                          
		COMMENT ON COLUMN V2_LOCALIZED_PROPERTY.PROPERTY_NAME    IS '프로퍼티 이름';                      
		COMMENT ON COLUMN V2_LOCALIZED_PROPERTY.PROPERTY_VALUE   IS '프로퍼티 값';                                

		
		CREATE TABLE V2_SEQUENCER (
		    SEQUENCER_ID           INTEGER NOT NULL,
		    NAME                   VARCHAR2(200) NOT NULL,
		    VALUE                  INTEGER NOT NULL,
		    CONSTRAINT V2_SEQUENCER_PK PRIMARY KEY (SEQUENCER_ID)
		); 				 
		
		CREATE UNIQUE INDEX V2_SEQUENCER_NAME_IDX ON V2_SEQUENCER (NAME);		
    
    COMMENT ON TABLE "V2_SEQUENCER"  IS '시퀀스 지원을 위한 테이블';    
		COMMENT ON COLUMN V2_SEQUENCER.SEQUENCER_ID      IS '시퀀스 아이디';                          
		COMMENT ON COLUMN V2_SEQUENCER.NAME              IS '시퀀스 이름';                      
		COMMENT ON COLUMN V2_SEQUENCER.VALUE             IS '시퀀스 값';    
		

		CREATE TABLE V2_I18N_TEXT (
		     TEXT_ID                   INTEGER NOT NULL,
		     NAME                      VARCHAR2(200)   NOT NULL,	     
		     TEXT                        VARCHAR2(2000)  NOT NULL,	
             CATEGORY_NAME     VARCHAR2(100)   NOT NULL,    
             LOCALE_CODE          VARCHAR2(100)   NOT NULL,
			 CREATION_DATE       DATE DEFAULT SYSDATE NOT NULL ,			 
		     MODIFIED_DATE       DATE DEFAULT SYSDATE NOT NULL ,
		     CONSTRAINT V2_I18N_TEXT_PK PRIMARY KEY (TEXT_ID)
		);				
		CREATE INDEX V2_I18N_TEXT_LOCALE_IDX ON V2_I18N_TEXT (LOCALE_CODE) ;
		CREATE UNIQUE INDEX V2_I18N_TEXT_NAME_IDX ON V2_I18N_TEXT (NAME, CATEGORY_NAME);	
		
		COMMENT ON TABLE "V2_I18N_TEXT"  IS 'I18N 지원을 위한 테이블';
		COMMENT ON COLUMN "V2_I18N_TEXT"."TEXT_ID" IS '국제화 텍스트 ID 값';	
		COMMENT ON COLUMN "V2_I18N_TEXT"."NAME" IS '국제화 텍스트 키 값';	
		COMMENT ON COLUMN "V2_I18N_TEXT"."TEXT" IS '국제화 텍스트 값';	
		COMMENT ON COLUMN "V2_I18N_TEXT"."CATEGORY_NAME" IS '카테고리 이름';	
		COMMENT ON COLUMN "V2_I18N_TEXT"."LOCALE_CODE" IS '로케일 코드 값';			
		COMMENT ON COLUMN "V2_I18N_TEXT"."CREATION_DATE" IS '생성일';	
		COMMENT ON COLUMN "V2_I18N_TEXT"."MODIFIED_DATE" IS '수정일';			
		
		

	    -- =================================================  
		--  COMPANY	
		-- =================================================		
		CREATE TABLE V2_COMPANY (
			  COMPANY_ID                INTEGER NOT NULL,
			  DISPLAY_NAME             VARCHAR2(255)   NOT NULL,
			  NAME                          VARCHAR2(100)   NOT NULL,
			  DESCRIPTION                VARCHAR2(1000)  NOT NULL,
			  CREATION_DATE            DATE DEFAULT  SYSDATE NOT NULL,
			  MODIFIED_DATE            DATE DEFAULT  SYSDATE NOT NULL,	
			  CONSTRAINT V2_COMPANY_PK PRIMARY KEY (COMPANY_ID)
		);
		
		CREATE INDEX V2_COMPANY_DATE_IDX ON V2_COMPANY(CREATION_DATE) ;		
		CREATE INDEX V2_COMPANY_NAME_IDX ON V2_COMPANY(NAME);			

		COMMENT ON TABLE      "V2_COMPANY"  IS '회사 테이블';
		COMMENT ON COLUMN "V2_COMPANY"."COMPANY_ID" IS '회사 ID'; 
		COMMENT ON COLUMN "V2_COMPANY"."NAME" IS '회사 이름'; 
		COMMENT ON COLUMN "V2_COMPANY"."DISPLAY_NAME" IS '출력시 보여줄 회사 이름'; 
		COMMENT ON COLUMN "V2_COMPANY"."DESCRIPTION" IS '설명'; 
		COMMENT ON COLUMN "V2_COMPANY"."CREATION_DATE" IS '생성일자'; 
		COMMENT ON COLUMN "V2_COMPANY"."MODIFIED_DATE" IS '수정일자'; 		
	
		
	    CREATE TABLE V2_COMPANY_PROPERTY (
		  COMPANY_ID               INTEGER NOT NULL,
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT V2_COMPANY_PROPERTY_PK PRIMARY KEY (COMPANY_ID, PROPERTY_NAME)
		);	
		COMMENT ON TABLE      "V2_COMPANY_PROPERTY"  IS '회사 프로퍼티 테이블';
		COMMENT ON COLUMN "V2_COMPANY_PROPERTY"."COMPANY_ID" IS '회사 ID'; 
		COMMENT ON COLUMN "V2_COMPANY_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
		COMMENT ON COLUMN "V2_COMPANY_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 		




        -- =================================================  
		--  User  	
		-- =================================================		    		
        -- 1. User
        CREATE TABLE V2_USER (
          COMPANY_ID          INTEGER NOT NULL,
		  USER_ID                  INTEGER NOT NULL,
		  USERNAME              VARCHAR2(100) NOT NULL,
		  PASSWORD_HASH    VARCHAR2(64)  NOT NULL,
		  NAME                   VARCHAR2(100),		  
		  NAME_VISIBLE           NUMBER(1, 0)  DEFAULT 1 ,
		  FIRST_NAME             VARCHAR2(100),		  
		  LAST_NAME              VARCHAR2(100),		
		  EMAIL                  VARCHAR2(100) NOT NULL,
		  EMAIL_VISIBLE          NUMBER(1, 0)  DEFAULT 1,
		  LAST_LOGINED_IN        DATE DEFAULT  SYSDATE NOT NULL,
		  LAST_PROFILE_UPDATE    DATE DEFAULT  SYSDATE NOT NULL,
		  USER_ENABLED           NUMBER(1, 0)  DEFAULT 1, 
		  VISIBLE                NUMBER(1, 0)  DEFAULT 1, 
		  IS_EXTERNAL            NUMBER(1, 0)  DEFAULT 0, 
		  FEDERATED              NUMBER(1, 0)  DEFAULT 0,
		  STATUS                 NUMBER(1, 0)  DEFAULT 0,
		  CREATION_DATE          DATE DEFAULT  SYSDATE NOT NULL,
		  MODIFIED_DATE          DATE DEFAULT  SYSDATE NOT NULL,		    
		  CONSTRAINT V2_USER_PK PRIMARY KEY (USER_ID)
		);		
		
		CREATE UNIQUE INDEX V2_USER_USERNAME_IDX ON V2_USER (USERNAME);
	    CREATE INDEX V2_USER_DATE_IDX ON V2_USER (CREATION_DATE) ;		
	    CREATE INDEX V2_USER_EXTERNAL_IDX   ON V2_USER (VISIBLE, USER_ENABLED, IS_EXTERNAL) ;	
	    		
	    CREATE INDEX V2_USER_COMPANY_IDX ON V2_USER (COMPANY_ID);
	    CREATE INDEX V2_USER_DATE_IDX2 ON V2_USER (COMPANY_ID, CREATION_DATE) ;		
	    CREATE INDEX V2_USER_EXTERNAL_IDX2 ON V2_USER (COMPANY_ID, VISIBLE, USER_ENABLED, IS_EXTERNAL) ;
	    
		COMMENT ON TABLE "V2_USER"  IS '애플리케이션 사용자 테이블';
		COMMENT ON COLUMN "V2_USER"."USER_ID" IS 'ID'; 
		COMMENT ON COLUMN "V2_USER"."USERNAME" IS '로그인 아이디'; 
        COMMENT ON COLUMN "V2_USER"."NAME" IS '전체 이름';
		COMMENT ON COLUMN "V2_USER"."PASSWORD_HASH" IS '암호화된 패스워드'; 
        COMMENT ON COLUMN "V2_USER"."NAME_VISIBLE" IS '이름 공개 여부';        
		COMMENT ON COLUMN "V2_USER"."FIRST_NAME" IS '이름'; 
        COMMENT ON COLUMN "V2_USER"."LAST_NAME" IS '성';        
		COMMENT ON COLUMN "V2_USER"."EMAIL" IS '메일주소'; 
        COMMENT ON COLUMN "V2_USER"."EMAIL_VISIBLE" IS '메일주소 공개여부';        
		COMMENT ON COLUMN "V2_USER"."LAST_LOGINED_IN" IS '마지막 로그인 일자'; 
        COMMENT ON COLUMN "V2_USER"."LAST_PROFILE_UPDATE" IS '마지막 프로파일 갱신 일자';        
		COMMENT ON COLUMN "V2_USER"."USER_ENABLED" IS '계정 사용여부'; 
        COMMENT ON COLUMN "V2_USER"."VISIBLE" IS '계정 공개 여부';	    
        COMMENT ON COLUMN "V2_USER"."IS_EXTERNAL" IS '외부 시스템에서 생성된 계정 여부';	    
        COMMENT ON COLUMN "V2_USER"."FEDERATED" IS '외부 계정과 연합 여부';	    
        COMMENT ON COLUMN "V2_USER"."STATUS" IS '계정 상태';	    
        COMMENT ON COLUMN "V2_USER"."CREATION_DATE" IS '생성일자';	    
        COMMENT ON COLUMN "V2_USER"."MODIFIED_DATE" IS '수정일자';	    
                
		-- 2. User properties data table.		        
        CREATE TABLE V2_USER_PROPERTY (
		  USER_ID                INTEGER NOT NULL,
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT V2_USER_PROPERTY_PK PRIMARY KEY (USER_ID, PROPERTY_NAME)
		);		
		
		COMMENT ON TABLE "V2_USER_PROPERTY"  IS '사용자 프로퍼티 테이블';
		COMMENT ON COLUMN "V2_USER_PROPERTY"."USER_ID" IS '사용자 ID'; 
		COMMENT ON COLUMN "V2_USER_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
		COMMENT ON COLUMN "V2_USER_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 
		
        -- =================================================  
		--  Group  	
		-- =================================================		
		-- 3. Group data table.
        CREATE TABLE V2_GROUP (
		  GROUP_ID                   INTEGER NOT NULL,
		  COMPANY_ID              INTEGER NOT NULL,
		  NAME                         VARCHAR2(100)   NOT NULL,
		  DISPLAY_NAME            VARCHAR2(255)   NOT NULL,
		  DESCRIPTION               VARCHAR2(1000)  NOT NULL,
		  CREATION_DATE           DATE DEFAULT  SYSDATE NOT NULL,
		  MODIFIED_DATE           DATE DEFAULT  SYSDATE NOT NULL,	
		  CONSTRAINT V2_GROUP_PK PRIMARY KEY (GROUP_ID)
		);
		
		-- CREATE INDEX V2_GROUP_DATE_IDX ON V2_GROUP(CREATION_DATE) ;	
		-- CREATE INDEX V2_GROUP_NAME_IDX ON V2_GROUP(NAME);
		
		CREATE INDEX V2_GROUP_COMPANY_IDX ON V2_GROUP(COMPANY_ID, GROUP_ID);
		CREATE INDEX V2_GROUP_NAME_IDX2 ON V2_GROUP(COMPANY_ID, NAME);
		CREATE INDEX V2_GROUP_DATE_IDX2 ON V2_GROUP(COMPANY_ID, CREATION_DATE) ;	
		 
		COMMENT ON TABLE "V2_GROUP"  IS '그룹 테이블';
		COMMENT ON COLUMN "V2_GROUP"."COMPANY_ID" IS '회사 ID'; 
		COMMENT ON COLUMN "V2_GROUP"."GROUP_ID" IS '그룹 ID'; 
		COMMENT ON COLUMN "V2_GROUP"."NAME" IS '그룹 KEY'; 
		COMMENT ON COLUMN "V2_GROUP"."NAME" IS '그룹 이름'; 
		COMMENT ON COLUMN "V2_GROUP"."DESCRIPTION" IS '설명'; 
		COMMENT ON COLUMN "V2_GROUP"."CREATION_DATE" IS '생성일자'; 
		COMMENT ON COLUMN "V2_GROUP"."MODIFIED_DATE" IS '수정일자'; 
				
		-- 4. Group Members
		CREATE TABLE V2_GROUP_MEMBERS (
		  GROUP_ID                    INTEGER NOT NULL,
		  USER_ID                       INTEGER NOT NULL,
		  ADMINISTRATOR           NUMBER(1, 0)  DEFAULT 0,
		  CREATION_DATE           DATE DEFAULT  SYSDATE NOT NULL,
		  MODIFIED_DATE           DATE DEFAULT  SYSDATE NOT NULL,	
		  CONSTRAINT V2_GROUP_MEMBERS_PK PRIMARY KEY (GROUP_ID, USER_ID, ADMINISTRATOR)
		);
		
		CREATE INDEX V2_GROUP_MEMBERS_USER_IDX ON V2_GROUP (USER_ID) ASC;		

		COMMENT ON TABLE "V2_GROUP_MEMBERS"  IS '그룹 멤버 테이블';
		COMMENT ON COLUMN "V2_GROUP_MEMBERS"."GROUP_ID" IS '그룹 ID'; 
		COMMENT ON COLUMN "V2_GROUP_MEMBERS"."USER_ID" IS '프로퍼티 이름'; 
		COMMENT ON COLUMN "V2_GROUP_MEMBERS"."ADMINISTRATOR" IS '관리자 구분'; 	
		COMMENT ON COLUMN "V2_GROUP_MEMBERS"."CREATION_DATE" IS '생성일자'; 
		COMMENT ON COLUMN "V2_GROUP_MEMBERS"."MODIFIED_DATE" IS '수정일자'; 					
		
		-- 5. Group Property
		CREATE TABLE V2_GROUP_PROPERTY (
		  GROUP_ID               INTEGER NOT NULL,
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT V2_GROUP_PROPERTY_PK PRIMARY KEY (GROUP_ID, PROPERTY_NAME)
		);	
		COMMENT ON TABLE "V2_GROUP_PROPERTY"  IS '그룹 프로퍼티 테이블';
		COMMENT ON COLUMN "V2_GROUP_PROPERTY"."GROUP_ID" IS '그룹 ID'; 
		COMMENT ON COLUMN "V2_GROUP_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
		COMMENT ON COLUMN "V2_GROUP_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 		
			

	    -- =================================================  
		--  ROLE  	
		-- =================================================
		 -- 6. Role 
		 CREATE TABLE V2_ROLE (
		  ROLE_ID                     INTEGER NOT NULL,
		  NAME                        VARCHAR2(100)   NOT NULL,
		  DESCRIPTION              VARCHAR2(1000)  NOT NULL,
		  MASK                         INTEGER NOT NULL,
		  CREATION_DATE           DATE DEFAULT  SYSDATE NOT NULL,
		  MODIFIED_DATE           DATE DEFAULT  SYSDATE NOT NULL,	
		  CONSTRAINT V2_ROLE_PK PRIMARY KEY (ROLE_ID)
		);
		
		COMMENT ON TABLE "V2_ROLE"  IS '롤 테이블';
		COMMENT ON COLUMN "V2_ROLE"."ROLE_ID" IS '롤 ID'; 
		COMMENT ON COLUMN "V2_ROLE"."NAME" IS '롤 이름'; 
		COMMENT ON COLUMN "V2_ROLE"."DESCRIPTION" IS '설명'; 	
		COMMENT ON COLUMN "V2_ROLE"."MASK" IS '마스크 값'; 	
		COMMENT ON COLUMN "V2_ROLE"."CREATION_DATE" IS '생성일자'; 
		COMMENT ON COLUMN "V2_ROLE"."MODIFIED_DATE" IS '수정일자'; 				
		
		CREATE UNIQUE INDEX V2_ROLE_NAME_IDX ON V2_ROLE (NAME)
		
		-- 7. User Roles 
		CREATE TABLE V2_USER_ROLES (
		  USER_ID                 INTEGER NOT NULL,
		  ROLE_ID                 INTEGER NOT NULL,
		  CONSTRAINT V2_USER_ROLES_PK PRIMARY KEY (USER_ID, ROLE_ID)
		);

		COMMENT ON TABLE "V2_USER_ROLES"  IS '사용자 롤 테이블';
		COMMENT ON COLUMN "V2_USER_ROLES"."USER_ID" IS '그룹 ID'; 
		COMMENT ON COLUMN "V2_USER_ROLES"."ROLE_ID" IS '롤 ID'; 
		
		-- 8. Group Roles 
		CREATE TABLE V2_GROUP_ROLES (
		  GROUP_ID                INTEGER NOT NULL,
		  ROLE_ID                 INTEGER NOT NULL,
		  CONSTRAINT V2_GROUP_ROLES_PK PRIMARY KEY (GROUP_ID, ROLE_ID)
		);
		
		COMMENT ON TABLE "V2_GROUP_ROLES"  IS '그룹 롤 테이블';
		COMMENT ON COLUMN "V2_GROUP_ROLES"."GROUP_ID" IS '그룹 ID'; 
		COMMENT ON COLUMN "V2_GROUP_ROLES"."ROLE_ID" IS '롤 ID'; 
		
		
	    -- =================================================  
		--  ATTACHEMENT 	
		-- =================================================		
		CREATE TABLE V2_ATTACHMENT (
	    		ATTACHMENT_ID			  INTEGER NOT NULL,
			  	OBJECT_TYPE                INTEGER NOT NULL,
			  	OBJECT_ID                   INTEGER NOT NULL,	    		
			   	CONTENT_TYPE             VARCHAR2(50)  NOT NULL,			  
			   	FILE_NAME                   VARCHAR2(255)   NOT NULL,
			   	FILE_SIZE                      INTEGER   NOT NULL,
			   	CREATION_DATE            DATE DEFAULT  SYSDATE NOT NULL,
			   	MODIFIED_DATE            DATE DEFAULT  SYSDATE NOT NULL,	
	    	   CONSTRAINT V2_ATTACHMENT_PK PRIMARY KEY (ATTACHMENT_ID)
	    
	    );
	    CREATE INDEX V2_ATTACHMENT_OBJ_IDX ON V2_ATTACHMENT( OBJECT_TYPE, OBJECT_ID ) ;	
		COMMENT ON TABLE "V2_ATTACHMENT"  IS '첨부파일 테이블';
		COMMENT ON COLUMN "V2_ATTACHMENT"."ATTACHMENT_ID" IS 'ID'; 
		COMMENT ON COLUMN "V2_ATTACHMENT"."OBJECT_TYPE" IS '첨부파일과 연관된 모델 유형'; 
        COMMENT ON COLUMN "V2_ATTACHMENT"."OBJECT_ID" IS '첨부파일과 연관된 모델 ID';
		COMMENT ON COLUMN "V2_ATTACHMENT"."FILE_NAME" IS '첨부파일 이름'; 
        COMMENT ON COLUMN "V2_ATTACHMENT"."FILE_SIZE" IS '첨부파일 크기';        
		COMMENT ON COLUMN "V2_ATTACHMENT"."CONTENT_TYPE" IS 'CONTENT TYPE 값'; 
		COMMENT ON COLUMN "V2_ATTACHMENT"."CREATION_DATE" IS '생성일'; 
        COMMENT ON COLUMN "V2_ATTACHMENT"."MODIFIED_DATE" IS '수정일';

        CREATE TABLE V2_ATTACHMENT_PROPERTY (
		  ATTACHMENT_ID               INTEGER NOT NULL,
		  PROPERTY_NAME          VARCHAR2(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR2(1024)  NOT NULL,
		  CONSTRAINT V2_ATTACHMENT_PROPERTY_PK PRIMARY KEY (ATTACHMENT_ID, PROPERTY_NAME)
		);	
		COMMENT ON TABLE      "V2_ATTACHMENT_PROPERTY"  IS '첨부파일 프로퍼티 테이블';
		COMMENT ON COLUMN "V2_ATTACHMENT_PROPERTY"."ATTACHMENT_ID" IS '첨부파일 ID'; 
		COMMENT ON COLUMN "V2_ATTACHMENT_PROPERTY"."PROPERTY_NAME" IS '프로퍼티 이름'; 
		COMMENT ON COLUMN "V2_ATTACHMENT_PROPERTY"."PROPERTY_VALUE" IS '프로퍼티 값'; 		

		CREATE TABLE V2_ATTACHMENT_DATA (
			  ATTACHMENT_ID                    INTEGER NOT NULL,
			  ATTACHMENT_DATA               BLOB,
			  CONSTRAINT V2_ATTACHMENT_DATA_PK PRIMARY KEY (ATTACHMENT_ID)
		);		        
		
		COMMENT ON TABLE "V2_ATTACHMENT_DATA"  IS '첨부파일 데이터 테이블';
		COMMENT ON COLUMN "V2_ATTACHMENT_DATA"."ATTACHMENT_ID" IS 'ID'; 
		COMMENT ON COLUMN "V2_ATTACHMENT_DATA"."ATTACHMENT_DATA" IS '첨부파일 데이터'; 		
		
	    -- =================================================  
		--  IMAGE	
		-- =================================================		
		CREATE TABLE V2_IMAGE (
			  IMAGE_ID                    INTEGER NOT NULL,
			  OBJECT_TYPE                INTEGER NOT NULL,
			  OBJECT_ID                   INTEGER NOT NULL,
			  FILE_NAME                   VARCHAR2(255)   NOT NULL,
			  FILE_SIZE                      INTEGER   NOT NULL,
			  CONTENT_TYPE             VARCHAR2(50)  NOT NULL,			  
			  CREATION_DATE            DATE DEFAULT  SYSDATE NOT NULL,
			  MODIFIED_DATE            DATE DEFAULT  SYSDATE NOT NULL,	
			  CONSTRAINT V2_IMAGE_PK PRIMARY KEY (IMAGE_ID)
		);		        
		
		
		CREATE INDEX V2_IMAGE_OBJ_IDX ON V2_IMAGE( OBJECT_TYPE, OBJECT_ID ) ;	
		COMMENT ON TABLE "V2_IMAGE"  IS '이미지 테이블';
		COMMENT ON COLUMN "V2_IMAGE"."IMAGE_ID" IS 'ID'; 
		COMMENT ON COLUMN "V2_IMAGE"."OBJECT_TYPE" IS '이미지와 연관된 모델 유형'; 
        COMMENT ON COLUMN "V2_IMAGE"."OBJECT_ID" IS '이미지와 연관된 모델 ID';
		COMMENT ON COLUMN "V2_IMAGE"."FILE_NAME" IS '이미지 파일 이름'; 
        COMMENT ON COLUMN "V2_IMAGE"."FILE_SIZE" IS '이미지 파일 크기';        
		COMMENT ON COLUMN "V2_IMAGE"."CONTENT_TYPE" IS 'CONTENT TYPE 값'; 
		COMMENT ON COLUMN "V2_IMAGE"."CREATION_DATE" IS '생성일'; 
        COMMENT ON COLUMN "V2_IMAGE"."MODIFIED_DATE" IS '수정일';
        
        CREATE TABLE V2_IMAGE_DATA (
			  IMAGE_ID                    INTEGER NOT NULL,
			  IMAGE_DATA               BLOB,
			  CONSTRAINT V2_IMAGE_DATA_PK PRIMARY KEY (IMAGE_ID)
		);		        
		
		COMMENT ON TABLE "V2_IMAGE_DATA"  IS '이미지 데이터 테이블';
		COMMENT ON COLUMN "V2_IMAGE_DATA"."IMAGE_ID" IS 'ID'; 
		COMMENT ON COLUMN "V2_IMAGE_DATA"."IMAGE_DATA" IS '이미지 데이터'; 		
				
        